declare namespace playstore {
  // Generated by https://quicktype.io
  interface PlaystoreItem {
    'Android Ver': string;
    'Content Rating': string;
    'Current Ver': string;
    'Last Updated': string;
    App: string;
    Category: string;
    Genres: string;
    Installs: string;
    Price: string;
    Rating: string;
    Reviews: string;
    Size: string;
    Type: string;
  }
}