export const intro = () => import('./views/OrderFromChaos.vue')
export const reactivity = () => import('@/views/vue/Reactivity.vue')
export const grouping = () => import('./views/PrinciplesOfGrouping.vue')
export const gestalt = () => import('./views/GestaltTheory.vue')
export const variables = () => import('./views/VisualVariables.vue')
export const slots = () => import('@/views/vue/Slots.vue')
export const sfc = () => import('@/components/workshop/vue/BasicComponent.vue')